version: "3"
services: 
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - "3000:3000"
    volumes: 
    - .:/usr/app
  backend:
    build:
      context: ../evento_chatbotservice_api
      dockerfile: Dockerfile.dev
    ports:
    - "5000:5000"
    volumes: 
    - ../evento_chatbotservice_api:/usr/app
